apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: dev
    name: data-platform-dev
    tier: platform
  name: data-platform-dev
---
apiVersion: v1
data:
  email: ZGV2QGV4YW1wbGUuY29t
  password: ZGV2X3BnYWRtaW5fcGFzcw==
kind: Secret
metadata:
  labels:
    environment: dev
    tier: platform
  name: dev-pgadmin-secret
  namespace: data-platform-dev
type: Opaque
---
apiVersion: v1
data:
  password: ZGV2X3Bhc3N3b3JkXzEyMw==
kind: Secret
metadata:
  labels:
    environment: dev
    tier: platform
  name: dev-postgres-secret
  namespace: data-platform-dev
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-db
  namespace: data-platform-dev
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: airbyte
    component: database
    environment: dev
    tier: platform
---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-server
  namespace: data-platform-dev
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: airbyte
    component: server
    environment: dev
    tier: platform
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-webapp
  namespace: data-platform-dev
spec:
  ports:
  - nodePort: 30081
    port: 80
    targetPort: 80
  selector:
    app: airbyte
    component: webapp
    environment: dev
    tier: platform
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
    environment: dev
    tier: platform
  name: dev-pgadmin
  namespace: data-platform-dev
spec:
  ports:
  - nodePort: 30080
    port: 80
    targetPort: 80
  selector:
    app: pgadmin
    environment: dev
    tier: platform
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    environment: dev
    tier: platform
  name: dev-postgres
  namespace: data-platform-dev
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
    environment: dev
    tier: platform
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-config-pvc
  namespace: data-platform-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-db-pvc
  namespace: data-platform-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-tmp-pvc
  namespace: data-platform-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-workspace-pvc
  namespace: data-platform-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  labels:
    environment: dev
    tier: platform
  name: dev-pgadmin-pvc
  namespace: data-platform-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    environment: dev
    tier: platform
  name: dev-postgres-pvc
  namespace: data-platform-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-db
  namespace: data-platform-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbyte
      component: database
      environment: dev
      tier: platform
  template:
    metadata:
      labels:
        app: airbyte
        component: database
        environment: dev
        tier: platform
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: airbyte_password
        - name: POSTGRES_DB
          value: airbyte
        - name: POSTGRES_USER
          value: airbyte
        image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: airbyte-db-data
      volumes:
      - name: airbyte-db-data
        persistentVolumeClaim:
          claimName: dev-airbyte-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-server
  namespace: data-platform-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbyte
      component: server
      environment: dev
      tier: platform
  template:
    metadata:
      labels:
        app: airbyte
        component: server
        environment: dev
        tier: platform
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://airbyte:airbyte_password@airbyte-db:5432/airbyte
        - name: CONFIG_ROOT
          value: /config
        - name: WORKSPACE_ROOT
          value: /workspace
        - name: LOCAL_ROOT
          value: /tmp/airbyte/local
        image: airbyte/server:0.50.4
        name: server
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: airbyte-config
        - mountPath: /workspace
          name: airbyte-workspace
        - mountPath: /tmp/airbyte
          name: airbyte-tmp
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z airbyte-db 5432; do echo waiting for airbyte database; sleep
          2; done
        image: busybox:1.35
        name: wait-for-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-webapp
  namespace: data-platform-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbyte
      component: webapp
      environment: dev
      tier: platform
  template:
    metadata:
      labels:
        app: airbyte
        component: webapp
        environment: dev
        tier: platform
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://airbyte-server:8001
        image: airbyte/webapp:0.50.4
        name: webapp
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z airbyte-server 8001; do echo waiting for airbyte server; sleep
          2; done
        image: busybox:1.35
        name: wait-for-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  labels:
    environment: dev
    tier: platform
  name: dev-airbyte-worker
  namespace: data-platform-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbyte
      component: worker
      environment: dev
      tier: platform
  template:
    metadata:
      labels:
        app: airbyte
        component: worker
        environment: dev
        tier: platform
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://airbyte:airbyte_password@airbyte-db:5432/airbyte
        - name: CONFIG_ROOT
          value: /config
        - name: WORKSPACE_ROOT
          value: /workspace
        - name: LOCAL_ROOT
          value: /tmp/airbyte/local
        image: airbyte/worker:0.50.4
        name: worker
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - mountPath: /config
          name: airbyte-config
        - mountPath: /workspace
          name: airbyte-workspace
        - mountPath: /tmp/airbyte
          name: airbyte-tmp
        - mountPath: /var/run/docker.sock
          name: docker-socket
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z airbyte-server 8001; do echo waiting for airbyte server; sleep
          2; done
        image: busybox:1.35
        name: wait-for-server
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: Socket
        name: docker-socket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
    component: database-admin
    environment: dev
    tier: platform
  name: dev-pgadmin
  namespace: data-platform-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
      environment: dev
      tier: platform
  template:
    metadata:
      labels:
        app: pgadmin
        component: database-admin
        environment: dev
        tier: platform
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              key: email
              name: dev-pgadmin-secret
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: dev-pgadmin-secret
        image: dpage/pgadmin4:8.0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 130
          periodSeconds: 20
        name: pgadmin
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/pgadmin
          name: pgadmin-data
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z $POSTGRES_SERVICE_NAME 5432; do echo waiting for postgres; sleep
          2; done
        env:
        - name: POSTGRES_SERVICE_NAME
          value: dev-postgres
        image: busybox:1.35
        name: wait-for-postgres
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: dev-pgadmin-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: postgres
    component: database
    environment: dev
    tier: platform
  name: dev-postgres
  namespace: data-platform-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      environment: dev
      tier: platform
  template:
    metadata:
      labels:
        app: postgres
        component: database
        environment: dev
        tier: platform
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: postgresdwhdev_dev
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: dev-postgres-secret
        image: postgres:latest
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U admin
          initialDelaySeconds: 30
          periodSeconds: 10
        name: postgres
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U admin
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: dev-postgres-pvc
